name: Run Foodsharing Script

on:
  schedule:
    - cron: "0 3 1 * *"   # jeden Monat am 1. um 03:00
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
   
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Playwright
        run: |
          pip install -r requirements.txt
          playwright install --with-deps chromium
 
      - name: Restore auth.json
        run: |
          echo "${{ secrets.AUTH_JSON_B64 }}" | base64 --decode > auth.json

      - name: Run script
        run: python fs2.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output/**/*.json

      - name: Commit results to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      
          mkdir -p data
          find output -type f -name "*.json" -exec cp {} data/ \;
      
          git add data || true
          if ! git diff --cached --quiet; then
            git commit -m "Automated data update for ${{ github.run_id }}"
            git push
          else
            echo "Keine Änderungen zum Commit."
          fi



      - name: Debug Excel file
        run: |
          echo "=== Dateien im Repo ==="
          ls -R .
          echo "=== Excel-Datei prüfen ==="
          ls -l excel/foodsharing.xlsx || true
          file excel/foodsharing.xlsx || true
          echo "=== Dateigröße ==="
          stat -c%s excel/foodsharing.xlsx || true



      - name: Update Excel file
        run: |
          pip install openpyxl
          python update_excel.py

      - name: Commit updated Excel
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add excel/foodsharing.xlsx || true
          if ! git diff --cached --quiet; then
            git commit -m "Excel updated for ${{ github.run_id }}"
            git push
          else
            echo "Keine Änderungen an Excel."
          fi
